services:
  magiclists:
    build:
      context: ../../../dockerfile/navidrome-magic-lists
      dockerfile: Dockerfile
    container_name: Navidrome-Magic-Lists
    ports:
      - 192.168.3.100:4545:8000
    network_mode: bridge
    env_file:
      - .env
    environment:
      - DATABASE_PATH=/app/data/magiclists.db
    volumes:
      - /volume2/docker/navidrome-magic-lists:/app/data
    restart: unless-stopped
volumes:
  magiclists_data:
    driver: local
